name: couple_signal
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.31+40

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.2
  # kakao login
  kakao_flutter_sdk: ^1.4.2
  dio: ^4.0.0
  json_annotation: ^4.0.1
  #  package_info: ^2.0.2
  package_info_plus: ^3.0.3
  platform: ^3.0.0
  # http
  http: ^0.13.3
  # FCM
  firebase_messaging: ^14.2.6
  # local notification
  #  flutter_local_notifications: ^8.0.0
  badges: ^3.0.2
  # provider
  provider: ^5.0.0
  # webview
  webview_flutter: ^3.0.4
  # location
  location: ^4.3.0
  # image_picker
  image_picker: ^0.8.2
  # spinkit
  flutter_spinkit: ^5.0.0
  # fontawesome
  font_awesome_flutter: ^10.1.0
  # table_calendar
  table_calendar: ^3.0.1
  # google_mobile_ads
  google_mobile_ads: ^0.13.4
  # firebase_core
  firebase_core: ^2.7.1
  # firebase_storage
  firebase_storage: ^11.0.15
  file_picker: ^5.2.1
  # carousel_slider
  carousel_slider: ^4.0.0
  # sign_in_with_apple
  sign_in_with_apple: ^3.3.0
  firebase_auth: ^4.2.10
  url_launcher: ^6.0.20
  flutter_local_notifications: ^9.5.2
  get_it: ^7.2.0
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/background_img.jpg
    - images/basic_profile_img.jpg
    - images/heartnal_bi.png
    - images/chinese_food.png
    - images/korean_food.png
    - images/western_food.png
    - images/pork_belly.png
    - images/dessert.png
    - images/samgyetang.png
    - images/random_choice.png
    - images/random_choice_2.png
    - images/daily_date.png
    - images/work_shop.png
    - images/park.png
    - images/bowling.png
    - images/art_gallery.png
    - images/cinema.png
    - images/zoo.png
    - images/amusement_park.png
    - images/botanical_garden.png
    - images/screen_baseball.png
    - images/screen_golf.png
    - images/ping_pong.png
    - images/billiards.png
    - images/shopping.png
    - images/coin_karaoke.png
    - images/drive.png
    - images/vr_game_room.png
    - images/roller_rink.png
    - images/board_game_room.png
    - images/library.png
    - images/bookstore.png
    - images/cafe.png
    - images/korean_sauna.png
    - images/main_2.png
    - images/main_3.png
    - images/main_1.png
    - images/beef.png
    - images/beef_brisket.png
    - images/bossam.png
    - images/chicken.png
    - images/chicken_feet.png
    - images/giblets.png
    - images/lamb_skewers.png
    - images/mak_chang.png
    - images/pork_feet.png
    - images/raw_meat.png
    - images/rib.png
    - images/bread.png
    - images/cake.png
    - images/churros.png
    - images/coffee.png
    - images/donut.png
    - images/hot_dog.png
    - images/ice_cream.png
    - images/pie.png
    - images/sandwich.png
    - images/shaved_ice.png
    - images/tart.png
    - images/waffle.png
    - images/doganitang.png
    - images/eel.png
    - images/galbitang.png
    - images/haesintang.png
    - images/sullungtang.png
    - images/yeonpotang.png
    - images/hamburger.png
    - images/pasta.png
    - images/pizza.png
    - images/rice_noodles.png
    - images/steak.png
    - images/tacos.png
    - images/curry.png
    - images/hwo_gwo.png
    - images/jajangmyeon.png
    - images/pork_cutlet.png
    - images/ramen.png
    - images/sashimi.png
    - images/sushi.png
    - images/agujjim.png
    - images/baegban.png
    - images/bibimbab.png
    - images/budaejjigae.png
    - images/doenjangjjigae.png
    - images/galbijjim.png
    - images/gamjatang.png
    - images/gejang.png
    - images/gimchijjigae.png
    - images/gimchijjim.png
    - images/gugbab.png
    - images/haejanggug.png
    - images/haemuljjim.png
    - images/jjimdalg.png
    - images/jjukkumi.png
    - images/jug.png
    - images/kalgugsu.png
    - images/konggugsu.png
    - images/korean_buffet.png
    - images/naengmyeon.png
    - images/snack_bar.png
    - images/sundubujjigae.png
    - images/tteogbokki.png
    - images/yuggaejang.png
    - images/donburi.jpg
    - images/title_eat_signal.png
    - images/title_play_signal.png
    - images/buffet.png
    - images/car_theater.png
    - images/cartoon_cafe.png
    - images/chueotang.png
    - images/escape_room_cafe.png
    - images/gomtang.png
    - images/kebab.png
    - images/malatang.png
    - images/olitang.png
    - images/roast_chicken.png
    - images/theater.png
    - images/have_a_drink.png
    - images/internet_cafe.png
    - images/signal.png
    - images/json/splash4.json
    - images/calendar/menstrual_cycle.jpg
    - images/calendar/ovulation.jpg
    - images/json/splash5.json
    - images/json/splash_sub.json
    - images/json/icon/icon_calendar.json
    - images/json/icon/icon_menstrual_calendar.json
    - images/json/icon/icon_signal_record.json
    - images/json/icon/icon_signal_status.json
    - images/json/icon/icon_signal.json
    - images/json/icon/icon_heart.json
    - images/json/icon/icon_eat_signal.json
    - images/json/icon/icon_message_of_the_day.json
    - images/json/icon/icon_play_signal.json
    - images/json/icon/icon_arrow_down.json
    - images/json/icon/icon_today_signal.json
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CookieRun
      fonts:
        - asset: fonts/CookieRun_Regular.ttf
    - family: GowunDodum
      fonts:
        - asset: fonts/GowunDodum-Regular.ttf
    - family: Cafe24SsurroundAir
      fonts:
        - asset: fonts/Cafe24SsurroundAir.ttf
    - family: Cafe24Ohsquareair
      fonts:
        - asset: fonts/Cafe24Ohsquareair.ttf
    - family: HS
      fonts:
        - asset: fonts/HS.ttf
    - family: KCC
      fonts:
        - asset: fonts/KCC.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
